"""empty message

Revision ID: 9be8f1bcbc2e
Revises: 25e83eab4007
Create Date: 2019-03-17 19:09:24.276370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be8f1bcbc2e'
down_revision = '25e83eab4007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('biography', sa.String(length=80), nullable=True))
    op.add_column('user_profiles', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('user_profiles', sa.Column('email', sa.String(length=80), nullable=True))
    op.add_column('user_profiles', sa.Column('gender', sa.String(length=80), nullable=True))
    op.add_column('user_profiles', sa.Column('location', sa.String(length=80), nullable=True))
    op.add_column('user_profiles', sa.Column('photo', sa.String(length=80), nullable=True))
    op.drop_constraint(u'user_profiles_username_key', 'user_profiles', type_='unique')
    op.drop_column('user_profiles', 'username')
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.create_unique_constraint(u'user_profiles_username_key', 'user_profiles', ['username'])
    op.drop_column('user_profiles', 'photo')
    op.drop_column('user_profiles', 'location')
    op.drop_column('user_profiles', 'gender')
    op.drop_column('user_profiles', 'email')
    op.drop_column('user_profiles', 'date')
    op.drop_column('user_profiles', 'biography')
    # ### end Alembic commands ###
